#!/bin/bash
set -e

# Set our DNS requirements
TTL=300
id=$(cut -d/ -f2 <<< $JUJU_UNIT_NAME)
ip=$(unit-get public-address)
relation-set domain=$(config-get zone)
# transmit a JSON with all the action .. make a sequencial build of the JSON for readability
RJSON=`printf '{"rr":"A","alias":"sipp-%s","ttl":"%s","addr":"%s"}' $id $TTL $ip`
relation-set resources="$RJSON"

# Update our DNS server
[ "$(relation-get private-address)" = "" ] || echo nameserver $(relation-get private-address) > /etc/resolvconf/resolv.conf.d/head
service resolvconf restart


# Update Clearwater configuration and restart
$CHARM_DIR/lib/config_script programmable-multiple
$CHARM_DIR/lib/restart
