#!/bin/bash

# This covers installing chef-solo and the Clearwater chef recipes
# Install chef and needed tools/libraries
apt-get -y install chef git libxml2-dev libxslt1-dev wget curl

# Pull down the Clearwater chef recipes
cd /home/ubuntu &&  tar xzf $CHARM_DIR/lib/chef-solo.tgz


# Create the solo.rb file
cat > /home/ubuntu/chef-solo/solo.rb <<EOP
file_cache_path "/var/chef-solo"
cookbook_path  [
    "/home/ubuntu/chef-solo/cookbooks"
]
data_bag_path "/home/ubuntu/chef-solo/data_bags"
environment_path "/home/ubuntu/chef-solo/environments"
role_path "/home/ubuntu/chef-solo/roles"
verbose_logging true
log_level :debug
EOP
