#!/bin/bash
set -e

# Get the configuration and action parameters.
home_domain=$(config-get zone)
number=$(action-get number)
password=$(action-get password)


# If the user doesn't exist, try to create them.  Otherwise, try to update them.
if ! sudo -S /usr/share/clearwater/bin/display_user $number $home_domain ; 
then
    echo "Subscriber doesn't exist - creating"
    sudo -S /usr/share/clearwater/bin/create_user $number $home_domain $password
else
  echo "Subscriber exists - updating"
  sudo -S /usr/share/clearwater/bin/update_user $number $home_domain --password $password
fi
