#!/bin/bash
set -e

# Set our DNS requirements
TTL=300
id=$(cut -d/ -f2 <<< $JUJU_UNIT_NAME)
ip=$(unit-get public-address)
relation-set domain=$(config-get zone)

# transmit a JSON with all the action .. make a sequencial build of the JSON for readability
RJSON=`printf '[ {"rr":"A","alias":"ellis","ttl":"%s","addr":"%s"}' $TTL $ip `
RJSON=$RJSON`printf ',{"rr":"A","alias":"ellis-%s","ttl":"%s","addr":"%s"}' $id $TTL $ip`
RJSON=$RJSON' ]'
relation-set resources="$RJSON"

## the result in you db.zone whould be :
#ellis '$TTL' IN A '$ip'
#ellis-'$id' '$TTL' IN A '$ip

# Update our DNS server
# Update our DNS server
[ "$(relation-get private-address)" = "" ] || echo nameserver $(relation-get private-address) > /etc/resolvconf/resolv.conf.d/head
service resolvconf restart

# Update Clearwater configuration and restart
$CHARM_DIR/lib/config_script programmable-multiple
$CHARM_DIR/lib/restart
